version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.25.0
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager/alert.rules/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=365d"
    network_mode: "host"

  grafana:
    image: grafana/grafana:7.4.2
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    network_mode: "host"

  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/templates/default.tmpl:/etc/alertmanager/templates/default.tmpl
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    network_mode: "host"

  blackbox:
    image: prom/blackbox-exporter:v0.18.0
    container_name: blackbox_exporter
    volumes:
      - ./blackbox:/config
    network_mode: "host"

  node_exporter:
    image: prom/node-exporter:v1.1.1
    container_name: node_exporter
    network_mode: "host"

volumes:
  prometheus-data:
  grafana-data:
